---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u adnan_dev -p y8@An5D!3bL8dvM
        - npx expo publish --non-interactive --release-channel development
        - expo build:android --non-interactive --release-channel deployment -t apk
        - expo build:ios --non-interactive -t simulator